from docx import Document
from docx.shared import Pt
import io
from pptx import Presentation
from pptx.util import Inches, Pt

def create_docx_from_markdown(text):
    """
    Converts simple Markdown text to a DOCX file object.
    Handling basic headers (#) and bullet points (-).
    """
    doc = Document()
    
    # Set default style if possible or just parse
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    for line in text.split('\n'):
        line = line.strip()
        if not line:
            continue
            
        if line.startswith('# '):
            doc.add_heading(line[2:], level=1)
        elif line.startswith('## '):
            doc.add_heading(line[3:], level=2)
        elif line.startswith('### '):
            doc.add_heading(line[4:], level=3)
        elif line.startswith('- ') or line.startswith('* '):
            doc.add_paragraph(line[2:], style='List Bullet')
        elif line.startswith('1. '):
            # Simple ordered list check
            doc.add_paragraph(line[3:], style='List Number')
        else:
            doc.add_paragraph(line)
            
    # Save to IO stream
    doc_io = io.BytesIO()
    doc.save(doc_io)
    doc_io.seek(0)
    return doc_io

from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'Intelligence Report', 0, 1, 'C')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def create_pdf_from_markdown(text):
    """
    Converts simple Markdown text to a PDF file object.
    """
    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    # Handle unicode characters broadly by assuming latin-1 for FPDF (limitation of basic FPDF)
    # properly we might need a utf-8 font, but for now let's try to encode/replace
    # or just clean the text
    
    for line in text.split('\n'):
        line = line.strip()
        if not line:
            pdf.ln(5)
            continue
            
        if line.startswith('# '):
            pdf.set_font("Arial", 'B', 16)
            pdf.cell(0, 10, line[2:].encode('latin-1', 'replace').decode('latin-1'), 0, 1)
            pdf.set_font("Arial", size=12)
        elif line.startswith('## '):
            pdf.set_font("Arial", 'B', 14)
            pdf.cell(0, 10, line[3:].encode('latin-1', 'replace').decode('latin-1'), 0, 1)
            pdf.set_font("Arial", size=12)
        elif line.startswith('### '):
            pdf.set_font("Arial", 'B', 13)
            pdf.cell(0, 10, line[4:].encode('latin-1', 'replace').decode('latin-1'), 0, 1)
            pdf.set_font("Arial", size=12)
        elif line.startswith('- ') or line.startswith('* '):
            pdf.cell(10) # Indent
            pdf.multi_cell(0, 5, chr(149) + " " + line[2:].encode('latin-1', 'replace').decode('latin-1'))
        elif line.startswith('1. '):
             pdf.cell(10)
             pdf.multi_cell(0, 5, line.encode('latin-1', 'replace').decode('latin-1'))
        else:
            pdf.multi_cell(0, 5, line.encode('latin-1', 'replace').decode('latin-1'))
            
    # Save to IO stream (as str for output logic, but streamlit needs bytes)
    # FPDF output() returns string in Py2, bytes/string in Py3 depending on args.
    # dest='S' returns as string.
    
    pdf_out = pdf.output(dest='S').encode('latin-1')
    return io.BytesIO(pdf_out)

def create_pptx_from_markdown(text):
    """
    Converts simple Markdown text to a PPTX file object.
    """
    prs = Presentation()
    
    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = "Intelligence Report"
    subtitle.text = "Generated by AI"
    
    # Content Slides
    bullet_slide_layout = prs.slide_layouts[1] # Title and Content
    
    current_slide = None
    body_text_frame = None
    
    for line in text.split('\n'):
        line = line.strip()
        if not line:
            continue
            
        if line.startswith('# ') or line.startswith('## '):
            # New Slide
            header_text = line.lstrip('#').strip()
            current_slide = prs.slides.add_slide(bullet_slide_layout)
            current_slide.shapes.title.text = header_text
            body_text_frame = current_slide.placeholders[1].text_frame
            body_text_frame.word_wrap = True
        
        elif line.startswith('- ') or line.startswith('* '):
            if body_text_frame:
                p = body_text_frame.add_paragraph()
                p.text = line[2:]
                p.level = 0
        
        elif line.startswith('1. '):
             if body_text_frame:
                p = body_text_frame.add_paragraph()
                p.text = line[3:]
                p.level = 0 
                
        else:
            # Regular text, add as bullet or paragraph
            if body_text_frame:
                p = body_text_frame.add_paragraph()
                p.text = line
                p.level = 0

    ppt_io = io.BytesIO()
    prs.save(ppt_io)
    ppt_io.seek(0)
    return ppt_io
